### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by asynts** [asynts/catnap#1]
- [ ] Use CUDA
- [ ] Make `VertShader` generic (i get an error message right now)
- [ ] Interpolate the output from `VertShader`.
- [ ] Maybe I don't have to make it generic and just use `Option`?
